server.port=8081

spring.datasource.url=jdbc:sqlite:cache.db
spring.datasource.driver-class-name=org.sqlite.JDBC

cache.ttl.seconds=3600
merkle.service.baseUrl=http://localhost:8082

logging.level.com.sd.laborator=INFO
